# Generated by Django 2.2.4 on 2019-08-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Circle Name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='Circle Description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified circles are also known as official community', verbose_name='Verified Circle')),
                ('is_public', models.BooleanField(default=True, help_text='Public circles are listed in the main page so everybody known about their existence')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited circles can grow up to fixed number of numbers')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If circle is limited, this will be the limit on the number of members')),
            ],
            options={
                'ordering': ('-rides_taken', '-rides_offered'),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
